entryPoints:
  web:
    address: ":80" # HTTP
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443" # HTTPS

certificatesResolvers:
  letsencrypt:
    acme:
      email: mathias@schulz.net.br
      storage: /acme/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: "server-network"

ping:
  entryPoint: "web"

api:
  dashboard: false
  insecure: false

log: # traefik logs
  level: "INFO"
  format: json
  filePath: "/var/log/traefik/traefik.log"
  maxSize: 100
  maxBackups: 3
  maxAge: 7
  compress: true

accessLog: # logs of each request to traefik
  format: json
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100
  maxSize: 100
  maxBackups: 3
  maxAge: 7
  compress: true
  filters:
    statusCodes:
      - "200-299"
      - "400-499"
      - "500-599"

global:
  checkNewVersion: false
  sendAnonymousUsage: false

http:
  middlewares:
    rate-limit: # max of 100 requisitions per second
      rateLimit:
        average: 100
        burst: 50
        period: 1s

    sec-headers:
      headers:
        browserXssFilter: true # XSS protection
        frameDeny: true # block site load on iframe
        customResponseHeaders:
          server: "" # remove header "Server: traefik" - don't expose software
          x-powered-by: "" # remove header "X-Powered-By: Express" - don't expose api framework
